@startuml stage_1_2_before

  class Welcomer
  class NativeClock
  Welcomer -down-> NativeClock

@enduml
@startuml stage_1_2_after

  class Welcomer
  interface Clock

  class SystemClock implements Clock
  class TestClock implements Clock


  Welcomer -down-> Clock
  SystemClock --> NativeClock

@enduml